    version: '3.8'
    services:

      muazin-mongo:
        image: mongo:latest
        container_name: muazin-mongo
        networks:
          - muazin-net
        ports:
          - "27017:27017"
        volumes:
          - mongo_data:/data/db

      muazin-kafka:
        image: bitnami/kafka:3.7
        container_name: muazin-kafka
        ports:
          - "9092:9092"
        networks:
          - muazin-net

      muazin-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: muazin-es
        environment:
          - xpack.security.enabled=false
#          - ES_JAVA_OPTS="-Xms1g -Xmx1g"
          - discovery.type=single-node
        ports:
          - "9200:9200"
        volumes:
          - elastic_data:/usr/share/elasticsearch/data
        networks:
          - muazin-net

      muazin-kibana:
        image: docker.elastic.co/kibana/kibana:8.15.0
        container_name: muazin-kibana
        environment:
          - ELASTICSEARCH_HOSTS=http://muazin-es:9200
        ports:
          - "5601:5601"
        depends_on:
          - muazin-es
        networks:
          - muazin-net

    volumes:
      elastic_data:
      mongo_data:

    networks:
      muazin-net:
        driver: bridge








#      muazin-kafka:
#        image: bitnami/kafka:3.7
#        container_name: muazin-kafka
#        environment:
#          - KAFKA_CFG_NODE_ID=1
#          - KAFKA_CFG_PROCESS_ROLES=broker,controller
#          - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#          - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#          - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#        ports:
#          - "9092:9092"
#        networks:
#          - muazin-net