    version: '3.8'
    services:
      muazin-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: muazin-es
        environment:
          - xpack.security.enabled=false
#          - ES_JAVA_OPTS="-Xms1g -Xmx1g"
          - discovery.type=single-node
        ports:
          - "9200:9200"
        volumes:
          - muazin-data:/usr/share/elasticsearch/data
        networks:
          - muazin-net

      muazin-kibana:
        image: docker.elastic.co/kibana/kibana:8.15.0
        container_name: muazin-kibana
        environment:
          - ELASTICSEARCH_HOSTS=http://muazin-es:9200
        ports:
          - "5601:5601"
        depends_on:
          - muazin-es
        networks:
          - muazin-net

    volumes:
      muazin-data:

    networks:
      muazin-net:
        driver: bridge